### ISSUE TITLE
Logo still clickable when hidden

### ISSUE THREAD

**Issue by maave0** [SiloCityLabs/blog#11]
the logo fades away but can still be accidentally clicked

![image](https://user-images.githubusercontent.com/1850819/59958459-1e2f1f80-9475-11e9-9154-5a2e3b99217e.png)

**Comment by ldrrp** [comment]
Lol

**Comment by ldrrp** [comment]
Also related maybe. Links are under logo on certain screen sizes

![image](https://user-images.githubusercontent.com/985837/60184489-26c98200-97f6-11e9-83de-7b31b2d6cab9.png)

**Comment by maave0** [comment]
the transition didn't work on width change but the visibility does so whatever
