### ISSUE TITLE
Remove JQuery

### ISSUE THREAD

**Issue by maave0** [SiloCityLabs/blog#33]
Try using this library

https://github.com/thednp/bootstrap.native

Hopefully it's a drop-in replacement and not too much manual work. We'll see about trimming CSS (Bootstrap) later.

**Comment by ldrrp** [comment]
Features needed:
- modal
- btn
- footer
- nav https://codepen.io/mutedblues/pen/MmPNPG
- form fields

**Comment by ldrrp** [comment]
Build custom fa package to icons used

**Comment by ldrrp** [comment]
http://fontello.com/

**Comment by maave0** [comment]
Extra SVGs to add to the font pack
Silabs icon: In google drive
[Hackaday icon](https://cdn.hackaday.io/files/1653147072794176/hackaday.svg)
[Thingiverse icon](https://camo.githubusercontent.com/aa27f1389a22e1542d42abe1f9961811c9529ee9/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f323933343034362f313930343639392f64316564343232632d376339332d313165332d393665652d6564326632366138373732382e706e67)

**Comment by ldrrp** [comment]
Could not find adequate Thingiverse icon.

**Comment by ldrrp** [comment]
Just need auto daemon processing of fontello-config.json file and bootstrap-config.json

**Comment by ldrrp** [comment]
Forgot we need to fix the dropdown jqueyr
