### ISSUE TITLE
Nested menu checker jquery code

### ISSUE THREAD

**Issue by ldrrp** [SiloCityLabs/blog#38]
Some commented out code left to migrate. Look at main.js

**Comment by maave0** [comment]
// Ensure nested navbar menus are not longer than the menu header

I think our theme solves this. We don't need the JS

![image](https://user-images.githubusercontent.com/1850819/62991862-56bcfb00-be1f-11e9-9810-5cfd34127857.png)

![image](https://user-images.githubusercontent.com/1850819/62991902-76ecba00-be1f-11e9-8a79-533d1b48fe8b.png)

**Comment by maave0** [comment]
Post screenshots if this is still an issue. Closing.
