### ISSUE TITLE
replace daemon with GitHub Actions

### ISSUE THREAD

**Issue by maave0** [SiloCityLabs/blog#39]
Implement the daemon using GitHub actions

https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/

waiting for github actions beta

**Comment by maave0** [comment]
[daemon.go](https://github.com/SiloCityLabs/blog/blob/master/daemon/daemon.go) psuedo-code

```
main()
	load settings from settings.yaml
		GithubSecret
		RootPath
	connect to github
	check the latest commit and set flags
		if only docs were modified, set dontBuildFlag
		if daemon was modified, set restartFlag
		if fontello was modified, set rebuildFontelloFlag
	if rebuildFontelloFlag, rebuildFontello()
	if !dontBuildFlag rebuildSite()
	if restartFlag, restart

rebuildFontello()	
	url = "http://fontello.com/"
	newfileUploadRequest(
		url	= url
		paramName = config
		file = ../themes/beautifulhugo/static/css/fontello-config.json
	)
	responseToken = response.body
	outputFile ("/tmp/fontello-" + responseToken + ".zip") = http.Get(url + responseToken + "/get")
	unzip outputFile
	delete ouputFile
	mv "fontello-embedded.css" "../themes/beautifulhugo/static/css/fontello-embedded.css"
	mv "fontello.eot" "../themes/beautifulhugo/static/font/fontello.eot"
	mv "fontello.svg" "../themes/beautifulhugo/static/font/fontello.svg"
	remove temp directory
	
rebuildSite()
	git pull
	Delete folders to regenerate
		/docs/page/
		/docs/categories/
		/docs/post/
		/docs/samples/
		/docs/tags/
		/docs/author/
	hugoOutput = exec.Command("hugo")
	git add .
	git commit -m "Webhook rebuild\n"+hugoOutput
	git push origin master
```

**Comment by maave0** [comment]
All accounts have beta access now. The workflow runs but Hugo updated and broke the theme. Update the theme. Or install Hugo 0.55.6 instead of the latest version, kick the can down the road.

**Comment by ldrrp** [comment]
0.58 fixed. Just need to finalize testing actions. Might report the bug about existing action files not showing up. 

Almost there, only issue now is github pages wont auto deply

**Comment by ldrrp** [comment]
Issues left:
 - Unreliable, only triggers for some file changes sometimes
 - Wont deploy to github pages environment (reported to github issues)

**Comment by ldrrp** [comment]
Last two issues fixed.

One more. Its infinit looping not detecting thr ignore for docs folder
