### ISSUE TITLE
Responsive youtube iframe

### ISSUE THREAD

**Issue by ldrrp** [SiloCityLabs/blog#6]
![Screenshot_20190620-200717_Chrome](https://user-images.githubusercontent.com/985837/59888718-1305c200-9397-11e9-8f4e-19ee6f000d0b.jpg)

**Comment by maave0** [comment]
https://silocitylabs.com/post/2018/11/23/secure-backups-without-the-cloud/

I don't think that's what's causing the issue. The youtube frames seem to scale, it's these code bits

![image](https://user-images.githubusercontent.com/1850819/60286026-e4c73b80-98dc-11e9-88c0-823011b48d8b.png)

break word on code

![image](https://user-images.githubusercontent.com/1850819/60286669-fceb8a80-98dd-11e9-9018-8ed04ce1d151.png)
