### ISSUE TITLE
Imported image captions

### ISSUE THREAD

**Issue by maave0** [SiloCityLabs/blog#8]
Captions aren't showing
ex:
https://silocitylabs.com/post/2018/02/06/using-laptop-ide-cables-for-2mm-pitch-headers/

**Comment by ldrrp** [comment]
It should generate like this, just have to figure out how to override the default template. I have it styled already for this.

```
<figure>
  <img src="{{ .img.src }}" alt="{{ .img.alt }}"/>
  <figcaption>{{ .img.alt }}</figcaption>
</figure>
```

**Comment by ldrrp** [comment]
Related to issue #12 see that issue first

**Comment by ldrrp** [comment]
Ended up going with shortcode, here it is. more article swaps now

```
{{< image src="/uploads/2019/06/golang-plugins-all.png" alt="Golang Install All">}}
{{< image src="/uploads/2019/06/golang-plugins-all.png" alt="Golang Install All" caption="title">}}
```

**Comment by ldrrp** [comment]
@maave0 you might wan add captions where you feel is needed. then close this.

**Comment by ldrrp** [comment]
Also amp support has a slight flaw of not being able to support external img urls becouse not knowing sizes. Although actually i can have the sizes be in the shortcode manually for external links

**Comment by ldrrp** [comment]
```
{{< image src="http://externalsite.com/uploads/2019/06/golang-plugins-all.png" alt="Golang Install All" caption="title" width="1920" height="1080">}}
```
